# Generated by Django 4.2.4 on 2023-10-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPatient',
            fields=[
                ('hospital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ethnic_code', models.CharField(choices=[('01', 'Dalit'), ('02', 'Janjati'), ('03', 'Madhesi'), ('04', 'Muslim'), ('05', 'Brahmin/Chhetri'), ('06', 'Others')], max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('district', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('1', 'General'), ('2', 'CB-IMNCI'), ('3', 'Nutrition'), ('4', 'Safe Motherhood'), ('5', 'Family Planning'), ('6', 'Tuberculosis'), ('7', 'Leprocy'), ('8', 'Vector Borne Disease'), ('9', 'STI'), ('10', 'Non Communicable Diseases'), ('11', 'Others')], max_length=5)),
                ('is_revisit', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
            ],
        ),
    ]
