# Generated by Django 4.2.4 on 2024-01-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newpatient',
            options={'ordering': ['first_name']},
        ),
        migrations.RemoveField(
            model_name='newpatient',
            name='registration_date',
        ),
    ]
